spring:
  application:
    name: ii-ne-bot-publisher
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: default
  web:
    resources:
      add-mappings: false
  cloud:
    stream:
      bindings:
        favorite-in-0:
          destination:
            favorite
          group: fav-group
    gcp:
      project-id: ii-ne-bot

server:
  max-http-header-size: 8KB
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  info:
    git:
      mode: full

  health:
    redis:
      enabled: false

logging.level:
  org.springframework.web.bind.annotation.RestController: debug
