# Java 11 を使う
runtime: java11

# Java 8 ランタイムの F1 ではメモリが 128MB だったが Java 11 では 256MB
instance_class: B4

includes:
  - secret.yaml

# 環境変数を設定
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=1024m -XX:ActiveProcessorCount=2 -Xmx32m"
  SPRING_PROFILES_ACTIVE: "prod"
